# Generated by Django 4.2.5 on 2023-09-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now=True)),
                ("details", models.CharField(max_length=255)),
                ("withdraw", models.FloatField(null=True)),
                ("deposit", models.FloatField(null=True)),
                ("balance", models.FloatField()),
            ],
        ),
    ]
