# Generated by Django 4.2.5 on 2023-09-27 09:12

import customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, help_text='300 characters maximum.', max_length=300, null=True, verbose_name='Biographie')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=customer.models.user_directory_path, verbose_name='Photo of profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
