# Generated by Django 4.2.5 on 2023-09-27 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IncomeCategories",
            new_name="ExpensesCategory",
        ),
        migrations.RenameModel(
            old_name="ExpensesCategories",
            new_name="IncomeCategory",
        ),
    ]
